name: BanditTest

on:
  push: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.10
        uses: actions/setup-python@v1
        with: 
          python-version: 3.7.10
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: run test with bandit
        run: bandit -r
